<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $report->report_number }} — {{ $report->title }}</title>
    <style>
        @page { margin: 42px 46px 54px; }
        * { box-sizing: border-box; }
        body { margin: 0; color: #172033; font-family: DejaVu Sans, sans-serif; font-size: 10px; line-height: 1.55; }
        h1, h2, h3, p { margin-top: 0; }
        h1 { margin-bottom: 5px; color: #0f172a; font-size: 19px; line-height: 1.25; text-transform: uppercase; }
        h2 { margin: 0 0 10px; padding-bottom: 6px; border-bottom: 1px solid #cbd5e1; color: #0f172a; font-size: 12px; text-transform: uppercase; }
        h3 { margin-bottom: 4px; color: #0f172a; font-size: 10px; }
        p { margin-bottom: 7px; }
        table { width: 100%; border-collapse: collapse; }
        th { color: #64748b; font-size: 7px; letter-spacing: .5px; text-align: left; text-transform: uppercase; }
        th, td { padding: 5px 7px; border: 1px solid #dbe3ee; vertical-align: top; }
        .document-header { padding-bottom: 15px; border-bottom: 2px solid #0f172a; }
        .brand { color: #64748b; font-size: 8px; font-weight: bold; letter-spacing: 1.1px; text-transform: uppercase; }
        .status { float: right; padding: 4px 8px; border: 1px solid #94a3b8; border-radius: 3px; color: #334155; font-size: 8px; font-weight: bold; }
        .meta { margin-top: 14px; }
        .meta td { width: 25%; padding: 0 14px 0 0; border: 0; }
        .label { display: block; margin-bottom: 2px; color: #64748b; font-size: 7px; font-weight: bold; letter-spacing: .5px; text-transform: uppercase; }
        .value { color: #0f172a; font-weight: bold; }
        .mono { font-family: DejaVu Sans Mono, monospace; font-size: 8px; }
        .introduction, .callout { padding: 10px 12px; border: 1px solid #dbe3ee; border-radius: 3px; background: #f8fafc; }
        .introduction { margin-top: 16px; color: #475569; font-style: italic; }
        .section { margin-top: 19px; page-break-inside: auto; }
        .section-number { display: inline-block; width: 19px; height: 19px; margin-right: 7px; border-radius: 50%; background: #0f172a; color: #fff; font-size: 8px; line-height: 19px; text-align: center; }
        .evidence-card { margin: 10px 0 14px; padding: 11px; border: 1px solid #dbe3ee; border-radius: 3px; page-break-inside: avoid; }
        .evidence-title { margin-bottom: 8px; font-size: 11px; font-weight: bold; }
        .evidence-number { margin-right: 7px; color: #1d4ed8; }
        .fact-grid td { width: 33.333%; border: 0; border-top: 1px solid #e2e8f0; padding: 7px 9px 3px 0; }
        .result { margin-top: 8px; padding: 8px 10px; border-radius: 3px; background: #eef6ff; color: #1e3a5f; }
        .warning { background: #fff1f2; color: #991b1b; }
        .timeline { margin: 6px 0 9px; padding-left: 11px; border-left: 2px solid #bfdbfe; }
        .timeline-item { margin-bottom: 7px; page-break-inside: avoid; }
        .muted { color: #64748b; }
        .conclusion { padding: 12px; border: 1px solid #cbd5e1; background: #f8fafc; color: #0f172a; font-weight: bold; }
        .technical { page-break-before: always; }
        .hash { word-break: break-all; font-family: DejaVu Sans Mono, monospace; font-size: 7px; }
        .document-footer { margin-top: 23px; padding-top: 9px; border-top: 1px solid #cbd5e1; color: #64748b; font-size: 7px; }
    </style>
</head>
<body>
    <header class="document-header">
        <span class="status">{{ $report->status }}</span>
        <div class="brand">H1 Digital Evidence Management System</div>
        <h1>Digital Evidence Integrity Report</h1>
        <div>{{ $report->title }}</div>
        <table class="meta">
            <tr>
                <td><span class="label">Report No.</span><span class="value mono">{{ data_get($snapshot, 'report.report_number') }}</span></td>
                <td><span class="label">Case No.</span><span class="value mono">{{ data_get($snapshot, 'case.case_number') }}</span></td>
                <td><span class="label">Generated by</span><span class="value">{{ data_get($snapshot, 'report.generated_by') }}</span></td>
                <td><span class="label">Generated</span><span class="value">{{ data_get($snapshot, 'report.generated_at') ? \Illuminate\Support\Carbon::parse(data_get($snapshot, 'report.generated_at'))->format('d M Y, H:i T') : 'Draft' }}</span></td>
            </tr>
        </table>
    </header>

    @if (data_get($snapshot, 'report.introduction'))
        <div class="introduction">{{ data_get($snapshot, 'report.introduction') }}</div>
    @endif

    <section class="section">
        <h2><span class="section-number">1</span>Case Summary</h2>
        <h3>{{ data_get($snapshot, 'case.title') }}</h3>
        <p>{!! nl2br(e(data_get($snapshot, 'case.summary') ?: 'No case summary was recorded.')) !!}</p>
    </section>

    <section class="section">
        <h2><span class="section-number">2</span>Evidence Included</h2>
        @foreach (data_get($snapshot, 'evidence', []) as $evidence)
            <article class="evidence-card">
                <div class="evidence-title"><span class="evidence-number mono">{{ $evidence['evidence_number'] }}</span>{{ $evidence['title'] }}</div>
                <table class="fact-grid">
                    <tr>
                        <td><span class="label">Type</span>{{ $evidence['type'] }}</td>
                        <td><span class="label">Registered by</span>{{ $evidence['registered_by'] ?: 'Not recorded' }}</td>
                        <td><span class="label">Current custodian</span>{{ $evidence['current_custodian'] ?: 'Not assigned' }}</td>
                    </tr>
                    <tr>
                        <td><span class="label">Registered</span>{{ \Illuminate\Support\Carbon::parse($evidence['registered_at'])->format('d M Y, H:i T') }}</td>
                        <td colspan="2"><span class="label">Physical source</span>{{ $evidence['physical_source'] ?: 'No physical source linked' }}</td>
                    </tr>
                </table>
                <div class="result {{ $evidence['integrity_warning'] ? 'warning' : '' }}">{{ data_get($evidence, 'verification.statement') }}</div>
            </article>
        @endforeach
    </section>

    <section class="section">
        <h2><span class="section-number">3</span>Integrity Explanation</h2>
        <p>{{ data_get($snapshot, 'integrity_explanation') }}</p>
        @foreach (data_get($snapshot, 'evidence', []) as $evidence)
            <div class="callout {{ $evidence['integrity_warning'] ? 'warning' : '' }}" style="margin-bottom: 7px">
                <strong class="mono">{{ $evidence['evidence_number'] }}</strong> — {{ data_get($evidence, 'verification.statement') }}
            </div>
        @endforeach
    </section>

    <section class="section">
        <h2><span class="section-number">4</span>Recorded Chain of Custody</h2>
        @foreach (data_get($snapshot, 'evidence', []) as $evidence)
            <h3><span class="mono">{{ $evidence['evidence_number'] }}</span> — {{ $evidence['title'] }}</h3>
            <p class="{{ $evidence['custody_warning'] ? 'warning callout' : 'muted' }}">{{ $evidence['chain_statement'] }}</p>
            @forelse ($evidence['custody'] as $event)
                <div class="timeline">
                    <div class="timeline-item">
                        <strong>{{ \Illuminate\Support\Carbon::parse($event['occurred_at'])->format('d M Y, H:i T') }}</strong><br>
                        {{ $event['from'] ?: 'Initial custody' }} → {{ $event['to'] ?: 'Unassigned' }}
                        @if ($event['purpose'])<br><span class="muted">{{ $event['purpose'] }}</span>@endif
                    </div>
                </div>
            @empty
                <p class="muted">No custody events were available in the preserved report snapshot.</p>
            @endforelse
        @endforeach
    </section>

    <section class="section">
        <h2><span class="section-number">5</span>Working Copies</h2>
        <p>{{ data_get($snapshot, 'working_copy_explanation') }}</p>
        @foreach (data_get($snapshot, 'evidence', []) as $evidence)
            @foreach ($evidence['working_copies'] as $copy)
                <div class="callout" style="margin-bottom: 7px">
                    <strong class="mono">{{ $copy['copy_id'] }}</strong> issued to {{ $copy['issued_to'] ?: 'an unrecorded recipient' }}
                    @if ($copy['purpose']) for {{ $copy['purpose'] }}@endif. Status: {{ $copy['status'] }}.
                </div>
            @endforeach
        @endforeach
    </section>

    <section class="section">
        <h2><span class="section-number">6</span>Findings</h2>
        @forelse (data_get($snapshot, 'findings', []) as $finding)
            <h3>{{ $finding['title'] }}</h3><p>{{ $finding['summary'] }}</p>
        @empty
            <p>{{ data_get($snapshot, 'findings_note') }}</p>
        @endforelse
    </section>

    <section class="section">
        <h2><span class="section-number">7</span>Conclusion</h2>
        <div class="conclusion">{{ data_get($snapshot, 'conclusion') }}</div>
    </section>

    @if ($technicalDetails)
        <section class="section technical">
            <h2>Technical Appendix</h2>
            <p class="muted">This appendix contains technical fingerprints and event-chain details for specialist review.</p>
            @foreach (data_get($technicalDetails, 'evidence', []) as $evidence)
                <article class="evidence-card">
                    <h3 class="mono">{{ $evidence['evidence_number'] }}</h3>
                    <span class="label">Registration fingerprint (SHA-256)</span>
                    <p class="hash">{{ $evidence['baseline_sha256'] }}</p>
                    <span class="label">Latest observed fingerprint</span>
                    <p class="hash">{{ $evidence['latest_observed_sha256'] ?: 'No later verification recorded' }}</p>
                    <p>{{ count($evidence['verification_history']) }} verification record(s), {{ count($evidence['custody_events']) }} custody event(s), and {{ count($evidence['derivatives']) }} derivative record(s) preserved.</p>
                </article>
            @endforeach
        </section>
    @endif

    <footer class="document-footer">
        <p><strong>{{ $deliveryType === 'PRINT' ? 'Print copy prepared' : 'Downloaded' }}:</strong> {{ $deliveredAt->format('d M Y, H:i T') }} by {{ $deliveredBy }}.</p>
        <p>This report describes records held by H1. A matching digital fingerprint makes later modification detectable; it does not independently establish the authenticity or truth of evidence before registration.</p>
        <p class="hash">Final report fingerprint: {{ $report->report_sha256 }}</p>
    </footer>
</body>
</html>
