<?php

namespace App\Enums;

enum EvidenceActivityType: string
{
    case EVIDENCE_REGISTERED = 'EVIDENCE_REGISTERED';
    case OFFLINE_SYNC_COMPLETED = 'OFFLINE_SYNC_COMPLETED';
    case WORKING_COPY_CREATED = 'WORKING_COPY_CREATED';
    case WORKING_COPY_ISSUED = 'WORKING_COPY_ISSUED';
    case WORKING_COPY_DOWNLOADED = 'WORKING_COPY_DOWNLOADED';
    case WORKING_COPY_EXPIRED = 'WORKING_COPY_EXPIRED';
    case WORKING_COPY_REVOKED = 'WORKING_COPY_REVOKED';
}
